### ISSUE TITLE
New CSS breaks styles on GeoExplorer

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#118]
<img width="988" alt="screenshot 2016-07-08 12 15 40" src="https://cloud.githubusercontent.com/assets/148380/16693969/c5012820-4505-11e6-90c6-147bba80de04.png">

**Comment by blewis** [comment]
This appears to be broken on production WorldMap

**Comment by ingenieroariel** [comment]
Can you post a screenshot here?

-a

**Comment by capooti** [comment]
@bglewis can this be closed or you still have the problem?
