### ISSUE TITLE
Need way to reduce spam Map creation

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#124]

**Comment by capooti** [comment]
@blewis what is the criterium to decide if a map is spam?

**Comment by blewis** [comment]
Great question.  Not sure but there is a ton of it being created.

Ben Lewis
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
Do we still need it @blewis?
We can discuss what could be the best way to implement this.
