### ISSUE TITLE
Create connector for Harvard Geospatial Library (HGL) WMS layers (and possibly other OGP participants)

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#130]
Will meet with Dave Siegel to determine best approach.  This might be particular to HGL or perhaps will be handled by creating an OGP (OpenGeoPortal connector) which would be ideal.

**Comment by capooti** [comment]
Yes, I think it should be fast. If not, we can postpone it to 1.5.1

**Comment by capooti** [comment]
So, according to the discussion of last week, should we postpone this to 1.5.1?
