### ISSUE TITLE
Usage data for remote layers pushed to Solr to improve search

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#135]
Information on maps a remote and local layer is in should be pushed to Solr to improve ranking.  Look at gathering this information from the JSON object we use to save the state of a map view as this will be a rich source for other usage information.  Other sources are Certification and Ranking (so far only for local layers). 

We also need uptime stat number pushed to solr to aid in search ranking.

**Comment by capooti** [comment]
I guess best option here is to have a scheduled script in Worldmap that parses all layers and maps and publish to Solr. This way we don't need to add too much overhead in the API
