### ISSUE TITLE
Require depict date (year) in layer upload and layer create

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#137]
Require depict date (year) in layer upload and layer create.  Also require depict date for layer added to warp.worldmap.

**Comment by capooti** [comment]
Is this information mandatory or can it be facultative?

**Comment by blewis** [comment]
I think at least an estimate should be mandatory.

**Comment by capooti** [comment]
Maybe a default value to current year?

**Comment by blewis** [comment]
No will want the user to put something in consciously.  Once we do this and get feedback we may want to also want to gather level of certainty.   Perhaps pulldown for plus or minus 1, 5, 10, 50, 100, 500, 1000 years.

**Comment by capooti** [comment]
Just to make sure: we want to add the depic date mandatory in the following two forms in GeoExplorer:

<img width="512" alt="screenshot 2016-10-03 17 29 13" src="https://cloud.githubusercontent.com/assets/148380/19054885/63d91584-898f-11e6-937c-847dbf63bcb1.png">

<img width="512" alt="screenshot 2016-10-03 17 28 49" src="https://cloud.githubusercontent.com/assets/148380/19054889/6ac1c350-898f-11e6-8445-86b1c39044a2.png">

I am wondering in which database field we have to insert this date. Looking at the metadata edit page, should be this date corresponding to "Temporal Extent Start Date" or to "Temporal Extent End Date"?

Or should we leave the GXP UI as it is, and should we make one of the two fields in the layer metadata page mandatory ("Temporal Extent Start Date" or to "Temporal Extent End Date")?

Note though that in the latter case we won't have the date if the user doesn't save the metadata.
