### ISSUE TITLE
Check if FastWFS is needed with GeoServer 2.9

### ISSUE THREAD

**Issue by mbertrand** [cga-harvard/geonode#14]
Use customized GeoServer (FastWFS), make sure it works w/GN2

https://github.com/cga-harvard/geoserver/tree/fastwfs_24x

**Comment by capooti** [comment]
I am changing the title (and assignees) of this from "Test modified GeoServer with GN2" to "Check if FastWFS is needed with GeoServer 2.9".
Not sure if the shard architecture could help in this respect (to avoid the FastWFS thing), if yes then we will need to shard the wmdata database wich contains 20k+ layers in monthly shards. From June 2016 we have a data shard every month containing about 400 layers.
If it is not a big customisation, we could check with GeoServer developers if we can include this in GeoServer core.
