### ISSUE TITLE
In hhypermap search approx 20,000 layers have bounding boxes around 0,0

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#146]
At least it appears this way zooming into 0,0 just off the coast of Ghana.
About 6k are Esri Map and about 14k seem to be from WorldMap and warper platforms

![image](https://cloud.githubusercontent.com/assets/812849/18993796/f3aee0de-86f2-11e6-948c-3643c89bc5e5.png)

**Comment by capooti** [comment]
I can look into this to see what can be the problem
