### ISSUE TITLE
New css theme messes up some control in the "Add Layers" dialog

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#150]
This can be seen in the hypersearch branch

<img width="896" alt="screenshot 2016-10-11 17 57 47" src="https://cloud.githubusercontent.com/assets/148380/19290170/6c5a8ae6-8fdc-11e6-9546-95b497b4a797.png">

<img width="896" alt="screenshot 2016-10-11 17 58 06" src="https://cloud.githubusercontent.com/assets/148380/19290177/70986e70-8fdc-11e6-8505-a04a59991dfe.png">

**Comment by capooti** [comment]
Note also the clipped radio buttons for permissions

**Comment by capooti** [comment]
I see only two problems that CSS introduced right now:

https://www.dropbox.com/s/g6d0ka3sczv7pcw/Screenshot%202016-11-25%2011.24.04.png?dl=0

https://www.dropbox.com/s/xw27us1l6xh2ggv/Screenshot%202016-11-25%2011.32.01.png?dl=0

**Comment by capooti** [comment]
We are still experiencing this problem @ingenieroariel

**Comment by capooti** [comment]
@ingenieroariel can you guys fix this? Thanks a lot!

**Comment by ingenieroariel** [comment]
Assigning to @lenninlasd
