### ISSUE TITLE
Many layers not getting indexed -- Had 200k layers at one point

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#161]
Most likely extent issue

**Comment by capooti** [comment]
This can be fixed only when fixing this: https://github.com/cga-harvard/HHypermap/issues/192

**Comment by capooti** [comment]
Extent of layers in Registry must be in mercator (-180, -90, 180, 90).
Otherwise coordinates of extent pushed to Solr will be rejected.
Currently we have more that 80k layers not having mercator extents.
