### ISSUE TITLE
Improve Map search along lines of Layer search (low priority)

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#208]

**Comment by capooti** [comment]
@bglewis can you provide some more info here?

**Comment by blewis** [comment]
Eventually it would be nice to enable users to search for maps as well as layers from the same search interface.

Ben Lewis
Geospatial Technology Manager
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
Search maps in the Layer Search interface of the map composer?
The one with the heatmap? Would it be useful to search for a map from within a map?
It can be done anyway, but it is not trivial as we would need to sync maps to the search engine as well

**Comment by blewis** [comment]
Yes.  There is now no way to search for the thousands of maps in worldmap.  This is a long term goal.  We don't need to worry about it now.

Ben Lewis
Geospatial Technology Manager
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
Well the main maps page has a text box for doing some basic search. Though it would be useful a visual representation, agreed
