### ISSUE TITLE
New CSS theme breaks the the Gazetteer tool

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#225]
New CSS breaks the Gazetteer tool (accessible by clicking on the "Gazetteer" button in any map). It is not possible anymore to select a different geocoder than the WorldMap one.

![screenshot 2017-04-10 11 23 03](https://cloud.githubusercontent.com/assets/148380/24869197/6b26d728-1de0-11e7-8edf-ff61ffe4cd58.png)

**Comment by capooti** [comment]
@ingenieroariel can this be fixed?

**Comment by Lenninlasd** [comment]
@capooti @ingenieroariel I enable the worldmap checkbox setting `disable: false` in GazetteerTool.js inside gxp plugins https://github.com/cga-harvard/gxp/blob/b5e9b4e684fb406490105bce44d665a61df328f1/src/script/plugins/GazetteerTool.js#L113

The new worldmap PR: https://github.com/cga-harvard/worldmap/pull/24/commits/efcef1de9bbcedd8134e682aec3714aa12b825b0

**Comment by capooti** [comment]
Thanks. We have in production the other repository: could you send the PR there as well?

**Comment by capooti** [comment]
http://g.recordit.co/3Sj6NvhANE.gif

**Comment by capooti** [comment]
the issue is caused by the file checked.png wich is missing from the repository
