### ISSUE TITLE
Gazetteer UI is broken

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#260]
Gazetteer UI in GeoExplorer doesn't return any results

**Comment by lannio** [comment]
When I execute "python manage.py migrate gazetteer", there is a problem.
Thank you.
![image](https://user-images.githubusercontent.com/33817803/37761951-0a85896a-2df6-11e8-81a1-8adecbce4575.png)

**Comment by capooti** [comment]
Do you have this directory in you github clone?
https://github.com/cga-harvard/geonode/tree/worldmap/geonode/contrib/worldmap/gazetteer/migrations

**Comment by lannio** [comment]
Yes, I have.
![image](https://user-images.githubusercontent.com/33817803/37807370-09da628a-2e80-11e8-8a1d-6080ce43da2e.png)

**Comment by lannio** [comment]
Sorry, I "cd geonode".  When I "cd camp", it is fine.

**Comment by capooti** [comment]
ok good to know. Sorry if instructions were not accurate.
