### ISSUE TITLE
layer's thumb_url is abnormal

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#284]
When I access my website with IP, the layer's thumb_url shows "localhost".
![default](https://user-images.githubusercontent.com/33817803/36718763-e333fc5e-1bdd-11e8-9623-34e920600be9.PNG)
![2](https://user-images.githubusercontent.com/33817803/36718764-e36993e6-1bdd-11e8-89b9-3b9c36337332.PNG)

**Comment by capooti** [comment]
@lannio this looks a configuration problem.
Where is worldmap-geonode running in your case?

**Comment by lannio** [comment]
I modified the configuration and I later uploaded the layer has no such problem.
