### ISSUE TITLE
Layers added from WordlMap search interface is not correctly added in GeoExplorer

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#285]
After I uploaded a layer, I can see it correctly in solr. But when I added the layer in, the address is displayed "http://localhost:8001//registry/hypermap..."
![1](https://user-images.githubusercontent.com/33817803/36731715-812b85e4-1c06-11e8-814c-c4a35e8c3839.png)
![2](https://user-images.githubusercontent.com/33817803/36731716-8177ff14-1c06-11e8-9909-d21a7cf1ecf5.png)
![3](https://user-images.githubusercontent.com/33817803/36732022-785880ce-1c07-11e8-80eb-bf4b6c4e7917.png)
![4](https://user-images.githubusercontent.com/33817803/36732030-817b58f2-1c07-11e8-8a9a-4ef98684269b.png)

**Comment by capooti** [comment]
Dear @lannio sorry for this problem.
You need to set the MAPPROXY_URL env var accordingly. I am updating the installation instructions and the local_settings.py.tmpl file with this information.
Let me know if this fixes the problem.

MAPPROXY_URL must point to the Hypermap URL, do you have Hypermap running at localhost:8001 in your case?

**Comment by capooti** [comment]
I have updated the tickle of the ticket.

**Comment by capooti** [comment]
@lannio checking better your error, it looks like WorldMap is trying to add the layer as a remote layer. Layers coming from local GeoServer will use GeoWebCache, and not MapProxy as in your case.
This was a previous problem I fixed last week, you need to update GeoExplorer as per this commit:
https://github.com/cga-harvard/geonode/commit/f9ffe2bbc2fec92112e60f76ccb6e5d29ef610a3

Which version of geonode-worldmap are you using? Make sure to git pull latest changes and you should be fine!

**Comment by lannio** [comment]
Thank you for your reply.
I modified the two parts to fix this problem.
The first is env_vars.
![1](https://user-images.githubusercontent.com/33817803/36765217-191d9126-1c6b-11e8-81bf-b29486d507d2.png)
The second is camp/camp/local_settings.py (geonode-project/project_name/local_settings.py.sample).
![2](https://user-images.githubusercontent.com/33817803/36765380-e2a345f4-1c6b-11e8-866a-e85fb304f4d6.png)
The original variable is like this.
![3](https://user-images.githubusercontent.com/33817803/36765405-febea3b4-1c6b-11e8-89ba-549b24d6eb3b.png)

**Comment by capooti** [comment]
env variables look fine to me now. Did you do a git pull to get latest version of GeoExplorer as per my previous comment?
Can you join our slack channel? I can help you there. Or if you prefer let's have a skype call?

**Comment by lannio** [comment]
I use the variables above and now I can search and load the layers normally.
Thank you for your help, I hope next week, please help me configure the server, let the system run faster, I will send you an email later about the time.
