### ISSUE TITLE
The saved map can not be opened normally

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#290]
I created a new map, searched and loaded a layer, and then I saved it. 
But after saving, the web page is refreshed and the layer can't be loaded properly. 
I think it's the problem of URL, when I load the layer，the layer's url is like "http://amap.zju.edu.cn:8001/registry/hypermap/layer/be64b830-c132-48f4-97e1-4ee0f4cd53f0/map/wmts/high_speed_rail_stations_2016_who/default_grid/6/51/28.png", but when I saved the map, the layer's url is like "http://amap.zju.edu.cn:8001/registry/hypermap/layer/be64b830-c132-48f4-97e1-4ee0f4cd53f0/map/wmts/geonode:high_speed_rail_stations_2016_who/default_grid/3/6/2.png".
There are more fields "geonode:" before the name of the layer.
![3](https://user-images.githubusercontent.com/33817803/36779107-d45d8b1a-1ca9-11e8-9115-34ba4d1ece77.jpg)
![4](https://user-images.githubusercontent.com/33817803/36779109-d5904a5e-1ca9-11e8-997d-021aa26275c3.jpg)
You can also visit amap.zju.edu.cn:8000 soon, but the 8001 port has not yet opened to the outside world, we have applied to open, and will be able to visit soon.

**Comment by capooti** [comment]
Dear @lannio I just tried with a remote layer, and I can successfully reopen the map:
http://128.31.22.73/maps/17/view

Is your layer local or remote? If it is local I think you are still using the old javascript version. Did you see this comment in the other issue (it is related):

> @lannio checking better your error, it looks like WorldMap is trying to add the layer as a remote layer. Layers coming from local GeoServer will use GeoWebCache, and not MapProxy as in your case.
> This was a previous problem I fixed last week, you need to update GeoExplorer as per this commit:
> f9ffe2b
> 
> Which version of geonode-worldmap are you using? Make sure to git pull latest changes and you should be fine!

**Comment by lannio** [comment]
I am sure I am using the latest version of code both geonode and hhypermap.
Everything is normal when I use the layer to create a new map, including identifying, modifying styles, saving, etc.
![7](https://user-images.githubusercontent.com/33817803/36848448-3068f6c2-1d9c-11e8-8f8f-564afe4bf24b.jpg)
![8](https://user-images.githubusercontent.com/33817803/36848451-30b7c158-1d9c-11e8-965d-8a38725c580f.jpg)
But when I use the solr to load layers, these functions are not available and can not be reloaded after saving.
![9](https://user-images.githubusercontent.com/33817803/36848494-57c31c8e-1d9c-11e8-97d3-1efb375c45ac.jpg)
![10](https://user-images.githubusercontent.com/33817803/36848495-581c7608-1d9c-11e8-8cc2-6844ac64b577.jpg)

**Comment by capooti** [comment]
As said, the problem is that your layer is not seen by WorldMap/GeoNode as a local layers. GeoNode local layers when added to the map will show their symbols in the legend, will let you edit the style and their features. Thus "Styles", "Create Feature" and "Edit Feture" should be enabled.
Furthermore, map tiles should not come from Hypermap MapProxy, as in your case, but from GeoServer GeoWebCache

![screenshot 2018-03-01 10 22 38](https://user-images.githubusercontent.com/148380/36852819-c776db22-1d3a-11e8-93f1-7e9d4528b43a.png)

Note how the layer tiles are generated by GeoServer (check the Request URL of the tile).

Can you make the URL accessible to try to debug this problem for you?

Meanwhile you can look at this map to see how a local layer should behave:
http://128.31.22.73/maps/23/view

**Comment by capooti** [comment]
Make sure you are using this GeoExplorer.js version:
https://github.com/cga-harvard/geonode/blob/f9ffe2bbc2fec92112e60f76ccb6e5d29ef610a3/geonode/contrib/worldmap/wm_extra/static/worldmap/worldmap_client/script/GeoExplorer.js

It must contain this line:
https://github.com/cga-harvard/geonode/blob/f9ffe2bbc2fec92112e60f76ccb6e5d29ef610a3/geonode/contrib/worldmap/src/geonode-client/app/static/script/app/GeoExplorer/GeoExplorer.js#L1166

**Comment by lannio** [comment]
I found the reason, some places are wrongly configured.
The type of service is set before the 'WMS', and now I changed to 'GeoNode worldmap'.
> url: http://localhost:8080/geoserver/ows? Type: Web Map Service (WMS)

![15](https://user-images.githubusercontent.com/33817803/36897220-a2405592-1e50-11e8-9a75-bee48389a4ba.jpg)
Now add layer with solr can be displayed and saved normally, but still can not modify the style. In 'http://128.31.22.73/maps/23/view' is the same problem, I think this may be https://github.com/cga-harvard/geonode/issues/283
![16](https://user-images.githubusercontent.com/33817803/36897447-864072d6-1e51-11e8-966a-e1032c455a67.jpg)

**Comment by capooti** [comment]
Excellent. I am fixing the problem with style editing soon, meanwhile if you logout and login again you should be able to edit it (it is because there is an auth token which expires after 24 hours)
Glad it is working now
