### ISSUE TITLE
Map download button is not normal

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#293]
The map download function is shown below.
There are only thumbnails.
![1](https://user-images.githubusercontent.com/33817803/36946517-e4e82c0e-1ff8-11e8-8a18-6ae718cd227a.jpg)

**Comment by capooti** [comment]
This is what we currently do in GeoNode for map download.
Would you like some particular map format implemented?

**Comment by capooti** [comment]
I am closing this @lannio 
let me know if you need further development for supporting any particular map formats.
