### ISSUE TITLE
The style of the layer metadata editing page is confusing

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#294]
![2](https://user-images.githubusercontent.com/33817803/36946644-b0f64424-1ffa-11e8-8ab2-3aaaafddb3ca.jpg)

**Comment by capooti** [comment]
Can't reproduce this in the demo site:

<img width="1205" alt="screenshot 2018-03-05 11 38 32" src="https://user-images.githubusercontent.com/148380/36987217-d2c73f9e-2069-11e8-955b-283c114dd896.png">

**Comment by capooti** [comment]
@lannio I am closing this as I am assuming this is caused by your CSS or configuration. Please let me know if you think my assumption is wrong.
