### ISSUE TITLE
New basemap cannot be displayed in the layer details page

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#302]
I added the base map of the Tianditu. 
In the map details page and create map page, it is used normally, but it cannot be loaded in the layer details page.
I found that the map details page and create map page use the code in the worldmap_client (I modified the code of the geonode_client and then compressed it into worldmap_client).
But the layer details page refers to the code in python_env. Should it be modified to use the code in the worldmap_client as well?
My modification is as follows: https://github.com/camp-zju/geonode/commit/b89000646f0df86b7d570a53025f08b8d970d220
Example is as follows: http://amap.zju.edu.cn/layers/geonode:qing_dai_qu_jia

![1](https://user-images.githubusercontent.com/33817803/37519023-a6efc264-2952-11e8-8d48-dc68e578d97d.png)

**Comment by capooti** [comment]
Yes, it should use the same geoexplorer version of the map composer. I am fixing this.

**Comment by capooti** [comment]
This is done.
