### ISSUE TITLE
Display of layers in map composer does not work for remote layers

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#306]
![image](https://user-images.githubusercontent.com/812849/37856387-993c8062-2eca-11e8-9c97-83a0963eab1e.png)

**Comment by capooti** [comment]
This was caused by Hypermap being down on the server. Could you please try this now and close the ticket?

**Comment by blewis** [comment]
I loaded a japan map warper layer and it worked.  A layer from Zhejiang server (which I would have thought was a remote layer) caused screen to go blank.    Should Zhejiang server be treated as local?  It is missing SRS presumably which would explain zoom problem.  Zhejiang layers show when "WorldMap Layers" filter is selected in Search tool but actual local layers from 128.31.22.73 do not.
