### ISSUE TITLE
Identify tools does not work

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#313]

**Comment by capooti** [comment]
@bglewis identify is working for me. Can you please send me a link to a map to replicate the problem? thanks

**Comment by blewis** [comment]
The layer in this map does not work for identify http://128.31.22.73/maps/44/view    No layer works in the map.  Identify works on layer page though

**Comment by lannio** [comment]
This also appears on our server.
I found that every time when I opened a map , I couldn’t identify.
But I can use it after I zoom or pan.(Maps and layers disappear https://github.com/cga-harvard/geonode/issues/309)
The above example is like this.

**Comment by blewis** [comment]
Yes we also have a ticket for that very annoying problem with map disappearing on zoom or pan, which is being caused by a bug in geonode where the projection srs is not getting handled right.  We are working hard to fix this soon.

**Comment by capooti** [comment]
This is fixed in our instance.
@lannio are you still experiencing this?
