### ISSUE TITLE
GeoFence raises an error

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#323]
![issue](https://user-images.githubusercontent.com/148380/38096045-e7fbda9e-333f-11e8-8f18-699b3be5b71e.jpg)

**Comment by capooti** [comment]
There are a few things which will help to avoid this error, accordingly to this thread: https://groups.google.com/forum/#!topic/h2-database/L0cqpwF2xeA

Could you provide the jvm args you are using, such as  -Xms -Xmx etc?

There are a few things which you could try, assuming your jvm is running with enough memory:

1. add h2.check false in variables as suggested in the link thread
2. use PostgreSQL instead than H2 for GeoFence. This is highly recommended for production

Let me know if this helped

**Comment by capooti** [comment]
Using PostgreSQL is really something which you should consider, especially if your instance will contain many layers (more than 100)

**Comment by lannio** [comment]
Sorry, I do not quite understand how to do it? 
Can you give me a detailed configuration method? Or please help us online.
Thank you.

**Comment by capooti** [comment]
@lannio ping me on the Slack/Skype chat whenever it is needed. I can provide further assistance

**Comment by capooti** [comment]
This was fixed.
