### ISSUE TITLE
Uploaded layers have skewed map extents

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#325]
See screenshot
![image](https://user-images.githubusercontent.com/812849/38215171-e692e028-3694-11e8-80cf-2789cd8987b2.png)

**Comment by blewis** [comment]
Another shot
![image](https://user-images.githubusercontent.com/812849/38215550-38041f70-3696-11e8-8069-629d182dbaba.png)

**Comment by blewis** [comment]
This layer has no layer page and displays over Boston but Zoom to Map Extent does not work
![image](https://user-images.githubusercontent.com/812849/38215719-b715e32a-3696-11e8-9a7a-b0b289b7f56c.png)

**Comment by capooti** [comment]
Thanks, will look into it.

**Comment by capooti** [comment]
This is now fixed. Please check and close the issue.
