### ISSUE TITLE
The identify function is broken

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#330]
![51](https://user-images.githubusercontent.com/33817803/38463193-7c3b3f58-3b27-11e8-8297-68b34039ad41.jpg)

**Comment by capooti** [comment]
thanks for reporting @lannio 
I will fix this ASAP

**Comment by capooti** [comment]
@blewis this is fixed. Could you close it?

**Comment by lannio** [comment]
Also fixed on my instance, thanks.
