### ISSUE TITLE
(Staging server) no Layers in Add Layers tool, no heatmap

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#332]

**Comment by capooti** [comment]
This is generally caused by Solr being down. It looks to happen often, as we are running the whole stack on a single instance, so it run out of ram.
In production we won't experience this.

**Comment by capooti** [comment]
Yes it is not a question of layers. It is the amount of RAM required by Django + GeoServer + Solr + Celery/RabbitMQ + PostgreSQL, which seems not enough on the staging server.
