### ISSUE TITLE
Layer disappears when one layer, one category in a Map

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#333]
Right click on "Overlays" in Map Composer.  Create new Category.  Drag an existing layer to the new category folder.  Layer disappears from map display and cannot be found.  Zoom to layer extent zooms to the correct extent.

**Comment by capooti** [comment]
This is happening when there is only one layer. With two or more layers I cannot replicate it.
I tested the same on WorldMap production, and the bug is there as well.
