### ISSUE TITLE
No more creating Thumbnail on save.  Tool exists which is part of metadata.  Just need default message/image "Thumbnail not yet set" in place of tthumbnail.

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#343]

**Comment by blewis** [comment]
There is thumbnail creation for layers which works automatically after a new layer is created.  This thumbnail is created by geoserver and so does not include base map in thumbnail.  The user can then set the thumbnail in the metadata and this uses HTML5 and captures the basemap as well.  The HTML5 approach can take 10 seconds or so we only use that when the user specifically asks for it in metadata.

For Maps we are not using geoserver because it can’t capture the map well with multiple layers so we put up a “Thumbnail not yet set for this map” message.  The user can then go into the metadata and set the thumbnail which uses HTML5.

**Comment by Niran814804102** [comment]
The two way of creating thumbnails for layers and maps is also working in camp server.

**Comment by capooti** [comment]
thanks for the feedback @Niran814804102
