### ISSUE TITLE
Map extents for remote layers not saved in map.  Special case.

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#345]
Load several remote layers from Japan server to map.  Save map.  Right click on layers and Zoom to layer.  Does not work.

**Comment by capooti** [comment]
duplicate

**Comment by capooti** [comment]
This is not trivial.

**Comment by capooti** [comment]
Didn't we decide to postpone this? It is a not trivial development, and currently legacy WorldMap is affected as well.

**Comment by blewis** [comment]
yes we can postpone
