### ISSUE TITLE
When deleting a layer, its entries in gazetteer are not removed

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#350]

**Comment by blewis** [comment]
I see features from layers which have been removed
![image](https://user-images.githubusercontent.com/812849/39448484-09ece334-4c93-11e8-9179-20df18a71de8.png)

**Comment by capooti** [comment]
Yes, this is happening if the layer was removed before the fix.
That can be fixed at database level, but at least the form is still returning results, unlikely before.

**Comment by capooti** [comment]
I though this is fixed @bglewis . I see it again in the sprint area?

**Comment by Niran814804102** [comment]
Thinks a lot, it's also working in our testing server.

**Comment by capooti** [comment]
great to know, thanks @Niran814804102
