### ISSUE TITLE
Thumbnail should be always generated for a layer, as it was before

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#351]
Now the generic "no thumbnail" image is used, which is intended for maps.

**Comment by capooti** [comment]
This was fixed already.

**Comment by blewis** [comment]
I think we were going to not create thumbnail automatically but have the user set it.

**Comment by capooti** [comment]
Right now: we don't create thumbnails when the layer is created, while we create thumbnail when the layer is uploaded. If you want to change this let me know.

**Comment by blewis** [comment]
Sounds good

**Comment by capooti** [comment]
Is this not fixed? Looking at the layers page I see the layers with the "no thumbnail" image.
