### ISSUE TITLE
Expand solr layer text search to handle any parts of strings

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#357]
For example "min" should return all records which have "min" somewhere in the title or description.
![image](https://user-images.githubusercontent.com/812849/39448221-48496338-4c92-11e8-98d2-b95aad2f5b5c.png)

Here are layers with "min" not returned.
![image](https://user-images.githubusercontent.com/812849/39448191-31ec6702-4c92-11e8-83be-43345a217c7c.png)

As first step could just have space, dash (implemented already) and underscores.

**Comment by blewis** [comment]
This might be as simple as adding underscore "_" in addition to dash "-" as string delimiter.  Ideally internal sting searching is supported but if that takes up a lot more space or is much less scalable we can go with a less resource intensive approach.

**Comment by blewis** [comment]
Any part of a string should be discoverable.    For example if someone were to type "discover" and there were records with titles or descriptions containing "discoverable", those records would be returned.

**Comment by capooti** [comment]
This is done, and will search any substring. It looks very fast, the indexing phase looks pretty fast as well.

Two things:

1) I manually configured Solr by adding the following fieldType in managed-schema:

```xml
<fieldType name="text_ngrm" class="solr.TextField" positionIncrementGap="100">
<analyzer type="index">
   <tokenizer class="solr.WhitespaceTokenizerFactory"/>
    <filter class="solr.NGramFilterFactory" minGramSize="1" maxGramSize="50"/>
 <filter class="solr.LowerCaseFilterFactory"/>
 </analyzer>
 <analyzer type="query">
   <tokenizer class="solr.WhitespaceTokenizerFactory"/>
   <filter class="solr.LowerCaseFilterFactory"/>
 </analyzer>
 </fieldType>
```

Then I changed the configuration for these copied fields, which are the ones which are searched by GeoExplorer Solr client, to use the new fieldType:

```xml
<field name="title_txt" type="text_ngrm"/>
<field name="abstract_txt" type="text_ngrm"/>
<field name="layer_originator_txt" type="text_ngrm"/>
<field name="layer_username_txt" type="text_ngrm"/>
```

Please create a ticket if you want this configuration  to be automatically generated by the Hypermap command which generates the Solr scheme.

2) The GeoExplorer search interface searches the "layer_username" instead than "layer_username_txt" field. If we want to do search using substring in the username field we need to change this. If you think this is needed please create another ticket.

**Comment by blewis** [comment]
now perhaps don't need "Layer List" search since we have "My Layers" in Solr search
