### ISSUE TITLE
When a layer is created the map extent is not set properly and so the thumbnail is not set properly by geoserver

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#358]
Later setting of thumbnail manually uses the HTML5 approach rather than the geoserver approach for setting the thumbnail.  This is ok.  Main issue is needing to have correct map extents for data layer created in the system and using them when setting the initial thumbnail, otherwise most layers will have blank thumbnails until manually set.   Here is example of layer created which has incorrect map extent:
http://128.31.22.73/layers/geonode:bentest11_test

**Comment by capooti** [comment]
thanks, I will check this.

**Comment by blewis** [comment]
For layers created in system geoserver assigns global extents.  This causes auto-generated thumbnail not to work.  So we will use Map approach and add message on thumbnails "Thumbnail not yet set for this Layer".  Layers which are uploaded will have Thumbnails auto generated because we will trust the map extents.

**Comment by capooti** [comment]
As a first thing I fixed the problem with layer extent. Now will look in thumbnail.

**Comment by capooti** [comment]
This is now fixed.

**Comment by blewis** [comment]
Layer display on layer page is very zoomed out.
![image](https://user-images.githubusercontent.com/812849/40026137-21f2cb3c-57a2-11e8-87cf-5708e8045948.png)

**Comment by capooti** [comment]
Unfortunately this is how GeoExplorer (OpenLayers) zoom to the global extent -180,-90,180,90.

**Comment by capooti** [comment]
What you have seen is based on old WorldMap code, and I agree that it is the expected behavior. We are now using GeoNode 2.8.0, which behaves like that instead. We can definitely fixes this at GeoNode code. If needed please create a new ticket specific for that (this one is related to a different issue which should be fixed now).

**Comment by blewis** [comment]
Layer creation is not working on staging
