### ISSUE TITLE
Document approach for Admin to create new set of categories

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#361]
New Categories to enable a different, custom set of categories.
Develop admin instructions for using the admin interface of Django for creating a new set of categories which will then work with the metadata input form and faceted search in geonode layer search.  Testing will be required in addition to documentation.

**Comment by capooti** [comment]
Here is a wiki page documenting how to implement custom categories: https://github.com/cga-harvard/geonode/wiki/How-to-customize-categories-in-GeoNode
