### ISSUE TITLE
Document a workflow for adding datasets with long text fields 

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#362]
Document a workflow between a scholar who creates a dataset using QGIS and an admin who loads the file to the CAMP system and registers it.  
Assume need to support length 10,000 Chinese characters.   Assuming long text fields will be searched from the map, will likely need to use full text indexing in PostGIS.  Check to see Identify and edit widgets support long text.

**Comment by capooti** [comment]
As a first thing I am fixing the updatelayers GeoNode command which appears to be broken in 2.8.0. I have reported it here: https://github.com/GeoNode/geonode/issues/3789

**Comment by capooti** [comment]
I created a wiki page with possible workflows. If needed I can extend/enrich the page:

https://github.com/cga-harvard/geonode/wiki/How-to-have-vector-datasets-supporting-long-text-fields-in-GeoNode

**Comment by blewis** [comment]
Thanks Paolo.  One thought.  If one were to want to quickly search such long text and if the geonode instance contained layers which contain many records with fields containing long text, one might want to use postres full text indexing? But since postres full text search is mainly for latin chars we might want to use pgroonga   https://pgroonga.github.io/ ?

**Comment by capooti** [comment]
I didn't know of this limit with PostgreSQL Full Text. Yes, it looks like we would need to use something like that. Or a search engine.

**Comment by blewis** [comment]
you mean like the Solr-based feature search we envisioned a while back?  Which would be easier, simpler, more likely to be adopted by geonode community?

**Comment by capooti** [comment]
I don't know anything about groonga, but it looks like an alternative to Solr? So why not using Solr as we have more experience with it?
Anyway, will need to read carefully the Groonga documentation to provide you with a better anwer.

**Comment by blewis** [comment]
I thought it used Postgres which might make it more useful for regular geonode users who do not install solr.  If not you can drop it.

**Comment by capooti** [comment]
I think it connects and sync PostgreSQL to Groonga and use Groonga to do full text search
