### ISSUE TITLE
Add long text field capability to Layer Creation tool

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#363]
Add long text field capability to Layer Creation tool.
Assume support for length of 10,000 Chinese characters.  Check edit and identify widgets for support of long text field.

**Comment by capooti** [comment]
This is already working. All string field created by the layer creation tool are defined as character varying in PostgreSQL, which let the user to add text of any size by default.

<img width="763" alt="screenshot 2018-05-11 11 11 12" src="https://user-images.githubusercontent.com/148380/39931911-bf19f928-550c-11e8-90cd-9ebdada080ce.png">
