### ISSUE TITLE
Sorting by layer or map in profile does not work (firefox not chrome on windows)

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#379]
![image](https://user-images.githubusercontent.com/812849/40061206-692acf66-5826-11e8-95b4-f3b7cb637db8.png)

**Comment by capooti** [comment]
This looks working to me. Which filter doesn't work for you?

**Comment by blewis** [comment]
None work

**Comment by capooti** [comment]
stack trace of error:
Error: event is not defined $scope.single_choice_listener@http://128.31.22.103/static/geonode/js/search/search.js?v=2.7.7.dev20180911153026:488:11 functionCall/<@http://128.31.22.103/static/lib/js/assets.min.js?v=2.7.7.dev20180911153026:35:13385 e@http://128.31.22.103/static/lib/js/assets.min.js?v=2.7.7.dev20180911153026:35:26596 $eval@http://128.31.22.103/static/lib/js/assets.min.js?v=2.7.7.dev20180911153026:34:4290 $apply@http://128.31.22.103/static/lib/js/assets.min.js?v=2.7.7.dev20180911153026:34:4504 compile/</<@http://128.31.22.103/static/lib/js/assets.min.js?v=2.7.7.dev20180911153026:35:26646 dispatch@http://128.31.22.103/static/lib/js/assets.min.js?v=2.7.7.dev20180911153026:4:14364 add/q.handle@http://128.31.22.103/static/lib/js/assets.min.js?v=2.7.7.dev20180911153026:4:11164
