### ISSUE TITLE
Use Haystack for search

### ISSUE THREAD

**Issue by mbertrand** [cga-harvard/geonode#38]
All previous work on haystack needs to be redone for new api

**Comment by capooti** [comment]
@bglewis I am thinking that most likely we will need to use haystack/solr for improving API performances in case we want to deploy the GeoNode search interface based on tastypie to end users (now they can just text search on maps, not on layers).
Maybe we can at a first stage use GeoNode without its layers and maps list page?

**Comment by capooti** [comment]
We can easily check if this will be needed in advance if we do the same test at #185
