### ISSUE TITLE
Upload of a shapefile with Chinese characters in field names fails

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#387]
This is a bug in GeoNode which I am checking out
https://github.com/GeoNode/geonode/issues/3818

**Comment by capooti** [comment]
This is a problem caused by the GeoServer REST API which seems unable to handle not ASCII characters. I filed the issue here: https://github.com/GeoNode/geonode/issues/3818
We need to wait for a fix in GeoServer.

**Comment by lannio** [comment]
ok，thank you very much.

**Comment by capooti** [comment]
This is now a regression in GeoNode and filed a ticket here:
https://github.com/GeoNode/geonode/issues/4025

**Comment by capooti** [comment]
This is now fixed thanks to this work from @afabiani 
https://github.com/GeoNode/geonode/commit/cc94e8211b14a861a7aa564fe144194c017f9630

It is needed to use the correct encoding though, which it is Windows CP1258 for the shapefile which was provided.
