### ISSUE TITLE
Updating the gazetteer with Chinese characters in field names fails

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#388]
Can't replicate until we fixes #387

**Comment by lannio** [comment]
I can't upload it right now. 
The layer I used to update the gazetteer was uploaded before this update. 
Layers already exist.

**Comment by capooti** [comment]
@lannio this look a regression in GeoServer from previous version. I created a ticket here: 
https://github.com/GeoNode/geonode/issues/3818

**Comment by capooti** [comment]
This is now fixed.
