### ISSUE TITLE
problem about updating map metadata.

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#389]
When updating information on the map metadata page, such as updating the title, it is mandatory to select categories and groups. 
http://128.31.22.73/maps/128/metadata_advanced
![image](https://user-images.githubusercontent.com/33817803/40756697-78432636-64b7-11e8-8e1b-1dd8989997e0.png)
![22](https://user-images.githubusercontent.com/33817803/40756871-41d1f608-64b8-11e8-8563-6389fcca84c9.jpg)
Problems occur after selecting categories and groups, and the map cannot be opened normally. 
![21](https://user-images.githubusercontent.com/33817803/40756865-3bf5d90c-64b8-11e8-85a6-93a79040e90e.jpg)
When the group was removed from the management page, the map returned to normal.
![image](https://user-images.githubusercontent.com/33817803/40756926-8380914a-64b8-11e8-88b9-bffb20cb8246.png)
In the 128 map, I didn't delete the group and keep the wrong status. You can see it.
http://128.31.22.73/maps/128

**Comment by lannio** [comment]
By the way, is it necessary to mandatory to select group and category when updating?

**Comment by capooti** [comment]
This is now working and it is not mandatory anymore to select group now.
