### ISSUE TITLE
Int and Float type fields are not editable in newly created layers

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#392]
Int and Float type fields are not editable in newly created layers

**Comment by capooti** [comment]
It is working for me on your layer:

<img width="819" alt="screenshot 2018-06-05 18 34 17" src="https://user-images.githubusercontent.com/148380/41006357-24ab8d74-68ef-11e8-9b6e-42c74e34a995.png">


Which error did you get?

**Comment by blewis** [comment]
No error message. Just couldn't write to the form for those fields. Tried Firefox and chrome on windows.
