### ISSUE TITLE
cannot create a new style in existing layer

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#397]

**Comment by capooti** [comment]
bug confirmed. It looks like only administrators are able to create new styles. I will need to debug it to figure out what is causing the problem.

**Comment by capooti** [comment]
This is happening in GeoNode 2.7.x as well, so we will come with a fix ASAP.

**Comment by capooti** [comment]
This is now working.

**Comment by capooti** [comment]
Not working for not-admin users.

**Comment by capooti** [comment]
fixed it.
