### ISSUE TITLE
Add two new CSV upload formats which support long text

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#403]
(Zhejiang request)
1) XY (Long/Lat):  CSV where point geometry is handled by X and Y columns.   Simple GUI solution is to require that "X" be used for Longitude and "Y" is used for Latitude.  That way we don't have to create a special GUI for it.  
2) Well Known Text: CSV where point, line, or poly geometry is handled by one field.  Simple GUI solution is to require that "geom" is used for geometry column.
All field names should be cap insensitive.

**Comment by capooti** [comment]
This is done.
