### ISSUE TITLE
Develop feature search

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#405]
Adapt the Gazetteer technology to support a general “Feature Search” capability.  To do this, the WM team will add a “Search” button next to the current “Gazetteer” button which enables users to search and highlight all features in all layers which have been added to a new feature search database by CAMP users.  In this way (unlike the local layer search at bottom left of UI), users don’t have to know ahead of time which layer to look in, and when they get results, they can zoom to feature location and also get to the layer the feature came from, so they can load that layer to the map if they wish.

**Comment by capooti** [comment]
I am closing this. We can open a new one when this will be needed.
