### ISSUE TITLE
Problem finding a new layer added to a map when map has many layers

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#408]
Zhejiang request to enable sorting of layers in map.
Easier solution may be to put any new layers added to a map into a folder at the top called "New".

**Comment by capooti** [comment]
Right now a layer is added on the category which is set in the metadata. If not, the layer would go to the "General" category. Do we need to rename "General" to "New"?

**Comment by blewis** [comment]
Maybe that would be the simplest solution.  Let's ask Lannio.

**Comment by capooti** [comment]
So what should we do with this one?

**Comment by capooti** [comment]
I am waiting from details from Wang on this.
