### ISSUE TITLE
Migrate Notes application

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#421]

**Comment by capooti** [comment]
This is done.

**Comment by blewis** [comment]
Thanks - small change if easy - change  "My Note:, "Comment", "Post a comment" text to normal text size but bold.  That is, same size as "responding to my own comment" text but bold.  
![image](https://user-images.githubusercontent.com/812849/49388699-8cd3a800-f6f2-11e8-864d-2a74ef64eb1f.png)
