### ISSUE TITLE
migrate the certification application

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#430]

**Comment by capooti** [comment]
done it.

**Comment by blewis** [comment]
When a layer is certified it shows up listed in the user's profile as certified by him/her.  That is one idea behind certification - it makes it possible to create a curated list of layers owned by many people, without making a map and loading them all to it.

**Comment by capooti** [comment]
I am not sure I understand.

Looking at this layer: http://worldmap.harvard.edu/data/geonode:bra_planning_districts_2015_zip_pnq

this is what I see:

<img width="432" alt="screenshot 2018-12-18 16 36 23" src="https://user-images.githubusercontent.com/148380/50184452-2ac69580-02e3-11e9-836a-79b1c4aa4ee4.png">

Now if I look at the migrated layer:

http://128.31.22.103/layers/geonode:bra_planning_districts_2015_zip_pnq

I see this:

![screenshot 2018-12-18 16 36 30](https://user-images.githubusercontent.com/148380/50184474-3914b180-02e3-11e9-873c-8a44f37f5628.png)

Isn't this the correct behaviour?

**Comment by blewis** [comment]
In legacy the certified layer shows up listed along with layers owned in the user profile.

**Comment by capooti** [comment]
gotcha, will add that.

**Comment by capooti** [comment]
This is now finalized. I added a link in the profile page which takes to the list of the certified layers and maps for that profile.

<img width="1153" alt="screenshot 2019-01-15 17 57 33" src="https://user-images.githubusercontent.com/148380/51215532-38c20300-18ef-11e9-8c43-e5b16fe22a21.png">

<img width="1190" alt="screenshot 2019-01-15 17 57 20" src="https://user-images.githubusercontent.com/148380/51215536-3c558a00-18ef-11e9-9a82-74a7f5ff65b5.png">
