### ISSUE TITLE
Safari cannot open the maps on the first page

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#449]

**Comment by capooti** [comment]
The reason could be that the cell phone does not switch automatically to the mobile view.
For example:

http://amap.zju.edu.cn/maps/1705/view

Should be accessed as http://amap.zju.edu.cn/maps/1705/mobile when using a mobile device.

Will look into it.

**Comment by camp-zju** [comment]
It can load the map in the homepage of camp server through cellphone now. It happened only some specific stituation or devices. I guess it is due to the cache of browers.

**Comment by capooti** [comment]
Thanks @camp-zju. I think we can close this @bglewis then
