### ISSUE TITLE
Map doesn't work if layer is updated

### ISSUE THREAD

**Issue by capooti** [cga-harvard/geonode#450]

**Comment by capooti** [comment]
I am waiting for more details from Wang. Keeping this open for now

**Comment by zju-niran** [comment]
You can try to replicate this in the following way:
1. login in as a non-admin user;
2. add a layer to a existed map which has already had a map;
3. save the map as a new map;
4. sign out and login in as admin;
5. edit the layer style of this new map and save the map;
6. clear the blowser cache and wait for a few time, now you can see the error in the map detail page.

**Comment by zju-niran** [comment]
In camp, we can not edit the layer style in the map using external network, which is the same with that in September. You can try to use rvpn([](https://rvpn.zju.edu.cn/por/login_psw.csp)) which is like a virtual personal server to connect the network of Zhejiang University.

**Comment by capooti** [comment]
hi @Niran814804102 we know about this problem. Please don't update CAMP until we fix all the existing bugs. We will let you know when to do the update. Thanks!

**Comment by zju-niran** [comment]
Sounds good.
