### ISSUE TITLE
Table view for layers (wish list)

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#58]
A table view for layers would be powerful.  Should support column sorting.  Highlight row should highlight feature on map. Editing in table.  Column naming.  Select columns for display.

**Comment by capooti** [comment]
This would be in the GeoExplorer client in GeoNode.
Unfortunately we don't have it in WM client, it can be done but it requires work.
Can this be postponed maybe @blewis ?

**Comment by blewis** [comment]
yes can be postponed
