### ISSUE TITLE
Limit downloads by size

### ISSUE THREAD

**Issue by blewis** [cga-harvard/geonode#87]
Disable downloads over a certain number of records and when over, display message to have people contact us for them.

"Sorry, the file you are attempting to download is quite large.  Please contact the system administrator with the URL for the layer you wish to download: worldmap@harvard.edu. Thank you."

**Comment by capooti** [comment]
we can adopt this approach.
Best thing to do in the long run, imho, is to have a procedure that export all of the layers (with ogr2ogr/gdal_translate) on a daily/weekly basis and serve them as static files.

**Comment by blewis** [comment]
Yes, or any files over a certain number of records?

**Comment by capooti** [comment]
Sure, we can have some criteria like that.

**Comment by capooti** [comment]
@bglewis we still need this, correct?
